name: BTC Price Bot

on:
  schedule:
    - cron: "2,7,12,17,22,27,32,37,42,47,52,57 * * * *"

jobs:
  send-price:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests python-telegram-bot

      - name: Send BTC price
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL: ${{ secrets.CHANNEL }}
        run: python bot.py
